### ISSUE TITLE
Dev setup, node-sass build errors

### ISSUE THREAD

**Issue by Arcanorum** [Arcanorum/dungeonz#164]
### Describe the bug

During the development setup, the `npm i` step fails during building the node-sass package.

### Notes

Noticed in #161 

```
C:\Users\Arcan\dungeonz>npm i

> dungeonz@0.0.1 postinstall
> cd server && npm install && cd ../client && npm install


added 466 packages, and audited 467 packages in 53s

found 0 vulnerabilities
npm ERR! code 1
npm ERR! path C:\Users\Arcan\dungeonz\client\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\Arcan\dungeonz\client\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\Arcan\\dungeonz\\client\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.11.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Arcan\dungeonz\client\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Arcan\dungeonz\client\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Arcan\dungeonz\client\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\Users\Arcan\dungeonz\client\node_modules\graceful-fs\polyfills.js:299:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:200:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Arcan\\dungeonz\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\Arcan\dungeonz\client\node_modules\node-sass
npm ERR! gyp ERR! node -v v15.11.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Arcan\AppData\Local\npm-cache\_logs\2021-08-08T15_50_32_740Z-debug.log
npm ERR! code 1
npm ERR! path C:\Users\Arcan\dungeonz
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c cd server && npm install && cd ../client && npm install

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Arcan\AppData\Local\npm-cache\_logs\2021-08-08T15_50_32_824Z-debug.log
```

### Environment

Windows 10

(using NVM for Windows)
NodeJS: 15.11.0
NPM: 7.6.0

**Comment by Arcanorum** [comment]
I haven't found anything conclusive as to what the problem is, but it seems to be to do with the unsupported NodeJS version 15.11.0 being used.

This project only officially supports Node 14.17.3 which is the latest LTS version.
Only the even numbered Node releases are considered stable.
The odd numbered ones are for new Node feature testing purposes and come with the disclaimer that anything may break.

The solution that worked for me on Windows:
I strongly recommend to use **NVM for Windows** (https://github.com/coreybutler/nvm-windows) to make switching between Node versions less troublesome.
Then use Node 14.17.3
`nvm install 14.17.3`
`nvm use 14.17.3`

Remove any global packages that may have been installed for a different node version just in case.
`npm cache clean --force`

Remove any existing node_modules in the project that have been partially installed just in case.
Delete node_modules in /dungeonz, /dungeonz/client and /dungeonz/server.

Then install the packages again.
/dungeonz: `npm i`

And it should work fine. It did for me at least. Any problems lmk.
