### ISSUE TITLE
Cannot add to drop list. Drop item name "GreenCap" does not exist in the items list.

### ISSUE THREAD

**Issue by Simperfy** [Arcanorum/dungeonz#92]
### Describe the bug

I carefully followed the [guide](https://github.com/Arcanorum/dungeonz/blob/master/guides/CREATURES.md) on creating a new Mob

### To reproduce

1. clone the repository

2. Create server/src/entities/destroyables/movables/characters/mobs/Slime.js
```js
const Mob = require("./Mob");

class Slime extends Mob {}
module.exports = Slime;
```

3. Create client/src/entitites/character/Slime.js
```js
import Character from "./Character";

class Entity extends Character {
  constructor(x, y, config){
    super(x, y, config);

    this.displayName.setText(dungeonz.getTextDef("Mob name: Slime"));
  }
}

Entity.prototype.animationSetName = "slime";

export default Entity;
```

4. Append to server/src/entities/destroyables/movables/characters/mobs/MobValues.yml
```yml
- name: Slime
  gloryValue: 60
  defence: 10
  viewRange: 5
  moveRate: 1200
  attackRate: 1500
  meleeDamageAmount: 15
  faction: HostileAnimals
  dropList:
    - itemName: GreenCap
      dropRate: 30
```

5. added with my own sprites
```
    client/assets/img/entities/characters/slime/slime-up-1.png
    client/assets/img/entities/characters/slime/slime-up-2.png
    client/assets/img/entities/characters/slime/slime-up-3.png
    client/assets/img/entities/characters/slime/slime-down-1.png
    client/assets/img/entities/characters/slime/slime-down-2.png
    client/assets/img/entities/characters/slime/slime-down-3.png
    client/assets/img/entities/characters/slime/slime-left-1.png
    client/assets/img/entities/characters/slime/slime-left-2.png
    client/assets/img/entities/characters/slime/slime-left-3.png
    client/assets/img/entities/characters/slime/slime-right-1.png
    client/assets/img/entities/characters/slime/slime-right-2.png
    client/assets/img/entities/characters/slime/slime-right-3.png

```

6. added SpawnerArea object using Tiled with `Slime` as `EntityClassName`
 
7. `npm run dev:server` 

<details>
 <summary><b>Error stack trace: (click me)</b></summary>
* Event names catalogue written to file.
* Start of index
* Started HTTP and WS servers on port 4567
* Populating items list.
* Spell book types catalogue written to file.
* Finished populating items list.
* Populating entities list.
* Chat warnings catalogue written to file.
* ERROR: Cannot add to drop list. Drop item name "GreenCap" does not exist in the items list.
         Check the name of the item to add is correct, and that it is in the items list.
Trace
    at Utils.error (/home/ragkhuza/Documents/workplace/dungeonz/server/src/Utils.js:114:17)
    at new Drop (/home/ragkhuza/Documents/workplace/dungeonz/server/src/gameplay/Drop.js:10:19)
    at /home/ragkhuza/Documents/workplace/dungeonz/server/src/entities/destroyables/movables/characters/mobs/MobStats.js:96:36
    at Array.forEach (<anonymous>)
    at new MobStats (/home/ragkhuza/Documents/workplace/dungeonz/server/src/entities/destroyables/movables/characters/mobs/MobStats.js:95:32)
    at /home/ragkhuza/Documents/workplace/dungeonz/server/src/entities/destroyables/movables/characters/mobs/MobStats.js:135:41
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/ragkhuza/Documents/workplace/dungeonz/server/src/entities/destroyables/movables/characters/mobs/MobStats.js:122:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
</details>

### Expected behaviour

Expected to see my newly Created Slime

### Browser
Firefox 85.0 (64-bit)

### Device
Ubuntu 20.04
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
16.0 GB
RTX 2060

**Comment by Simperfy** [comment]
Update: I figured out what cause the problem. I'm working on a PR to fix the typo.
